apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-pv
  namespace: {{ .Values.appNamespace }}
  labels:
    name: {{ .Values.appName }}-pv
    type: {{ .Values.volume.type }}
    context: {{ .Values.appContext }}
spec:
  capacity:
    storage: {{ .Values.volume.capacity }}
  volumeMode: Filesystem
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce #the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access (read from or write to) that volume when the pods are running on the same node. For single pod access, please see ReadWriteOncePod.
  persistentVolumeReclaimPolicy: Retain #Data is preserved even if the PVC is deleted.
  hostPath:
    path: {{ .Values.volume.hostPath }} 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeHostname }}
---
# Claims must exist in the same namespace as the Pod using the claim. 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-pvc
  namespace: {{ .Values.appNamespace }}
  labels:
    name: {{ .Values.appName }}-pvc
    type: {{ .Values.volume.type }}
    context: {{ .Values.appContext }}
spec:
  volumeName: {{ .Values.appName }}-pv
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
